newline_style = "Unix"
max_width = 140
fn_call_width = 120
tab_spaces = 4
fn_params_layout = "Compressed"
where_single_line = true
reorder_imports = true
indent_style = "Block"
chain_width = 120
reorder_modules = false
use_small_heuristics = "Max"
