name: CI

on:
  push:
  pull_request:

env: 
  CARGO_TERM_COLOR: always
  # Make sure CI fails on all warnings, including Clippy lints
  RUSTFLAGS: "-Dwarnings"

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608
      - uses: awalsh128/cache-apt-pkgs-action@1850ee53f6e706525805321a3f2f863dcf73c962
        with:
          packages: mpd
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cargo build --verbose
      - run: cargo test --verbose
      - if: matrix.toolchain == 'nightly'
        run: rustup component add rustfmt && cargo fmt --all -- --check
      - if: matrix.toolchain == 'stable'
        run: cargo clippy --all-features
      - if: matrix.toolchain == 'stable'
        run: cargo doc
